- name: Docker Compose Up/Down playbook
  hosts: web_servers
  become: true
  vars:
    compose_project_path: "{{ playbook_dir }}"
    compose_project_name: "mongodb"
  tasks:
    - name: Check Docker Compose status
      command: docker-compose -p {{ compose_project_name }} ps --services --filter "status=running"
      register: compose_status
      ignore_errors: true
      args:
        chdir: "/home/vivans/tech/"

    - name: Bring up Compose project if it's down
      command: docker-compose  up -d
      when: true
      args:
        chdir: "/home/vivans/tech/"

    - name: Bring down Compose project if it's up
      command: docker-compose down
      when: compose_status.rc == 0
      args:
        chdir: "/home/vivans/tech/"
