- name: Docker Compose Up/Down playbook
  hosts: web_servers
  become: true
  vars:
    compose_project_path: "/home/vivans/tech"
    compose_project_name: "mongodb"
  tasks:
    - name: Check Docker Compose status
      docker_compose:
        project_src: "{{ compose_project_path }}"
        project_name: "{{ compose_project_name }}"
        state: 'changed'
        validate_certs: no
      register: compose_status

    - name: Bring down Compose project if it's up
      docker_compose:
        project_src: "{{ compose_project_path }}"
        project_name: "{{ compose_project_name }}"
        state: 'absent'
        validate_certs: no
      when: compose_status.changed
